name: 'Neil Parmenter: What inspired me to be me?'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.72106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.017721099546179175
purpose: []
